### ISSUE TITLE
Start

### ISSUE THREAD

**Issue by rodolfobubb** [keithdmoore/ionic-http-auth#2]
I'm having trouble to init this server, when i type npm install :
npm ERR! Failed at the ionic-project@1.0.0 preinstall script.
npm ERR! This is most likely a problem with the ionic-project package,
npm ERR! not with npm itself.

and a blank page appears when i run the ionic serve.

**Comment by keithdmoore** [comment]
Try this `npm install -g ionic`  and then ionic serve

**Comment by rodolfobubb** [comment]
thank you

**Comment by keithdmoore** [comment]
Did that work?

**Comment by rodolfobubb** [comment]
yes
