### ISSUE TITLE
Missing JS files

### ISSUE THREAD

**Issue by guizmo** [keithdmoore/ionic-http-auth#3]
Hi there when i run npm install, the angular dependencies aren't fetched so on ionic serve i get js errors due to missing files :
- /lib/angular-mocks/angular-mocks.js 
- /lib/angular-local-storage/dist/angular-local-storage.js
- /lib/angular-http-auth/src/http-auth-interceptor.js

Would you have any idea what is going wrong ?

PS: I could just add them manually...

**Comment by keithdmoore** [comment]
Just add them manually.  Sorry, I should have set bower up for that

**Comment by guizmo** [comment]
that's ok. I just thought i was doing something wrong

**Comment by keithdmoore** [comment]
I deleted the libs and upgraded ionic to rc3.  After looking further, this project is setup to automatically pull in the deps.  You should just be able to execute `npm install`
