### ISSUE TITLE
lib folder not found

### ISSUE THREAD

**Issue by iiitmahesh** [keithdmoore/ionic-http-auth#7]
in index.html there are

 script src="lib/ionic/release/js/ionic.bundle.js"
    script src="lib/angular-mocks/angular-mocks.js"
    script src="lib/angular-local-storage/dist/angular-local-storage.js"

there is no lib file how could check app.please help me.(\* I am new to ionic and angular JS)

**Comment by keithdmoore** [comment]
Check out the readme and execute this: `npm install`

You will need to install node.js

**Comment by iiitmahesh** [comment]
Thank for your reply. I do have npm in my system.

error log messge in broswer (when I run this code )
The connection to ws://localhost:35729/livereload was interrupted while the page was loading. livereload.js:191:0
Firefox can't establish a connection to the server at ws://localhost:35729/livereload. livereload.js:191:0
ReferenceError: angular is not defined app.js:9:0
ReferenceError: angular is not defined services.js:1:0
ReferenceError: angular is not defined controllers.js:1:0

**Comment by keithdmoore** [comment]
I would recommend that you use Chrome

**Comment by iiitmahesh** [comment]
Thank you very much. Problem was resolved adding all dependencies.(placing all required files in their respective locations) add also running every browser. 

link rel="stylesheet" href="lib/ionic/css/ionic.css"
    link rel="stylesheet" href="css/style.css" 
    script src="lib/ionic/js/ionic.bundle.js
    script src="lib/angular-mocks/angular-mocks.js"
    script src="lib/angular-local-storage/angular-local-storage.min.js"
    script src="lib/http-auth-interceptor.js"
